languageCode = "pt-pt"
languageName = "PortuguÃªs"
weight = 1
title = "ELOY Devotional"

[params]
  displayName = "PT-PT"
  isoCode = "pt-PT"
  rtl = false
  logo = "img/logo.png"
  description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"
  dateFormat = "2 January 2006"
