languageCode = "pt-pt"
languageName = "PortuguÃªs"
weight = 1
title = "ELOY Devotional"

[params]
  displayName = "PT-PT"
  isoCode = "pt-PT"
  rtl = false
  # logo = "img/logo.png"
  description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"
  dateFormat = "2 January 2006"

[params.author]
  name = "Red Blowfish"
  image = "img/avatar.png"
  headline = "This is my website with my links"
  bio = "A little bit about you"
   links = [
     { link = "https://nunocoracao.github.io/blowfish/" },
     { github = "https://github.com/nunocoracao/blowfish" },
     { x-twitter = "https://twitter.com/burufugu" }
   ]
